Challenge
```
In RSA d is a lot bigger than e, why don't we use d to encrypt instead of e? Connect with nc jupiter.challenges.picoctf.org 19566
```
Connecting to it gave me the values
```
c: 10053284367692092408060534432233781784294923528212355187383526910927871066651583744637289085781456421980473491209482413938046982135479068839655873058602979592685277822007493317921218411757164957737640844095430827381520163245525364943143755308164241740933293587239366002651923964673511284584594740402129716515
n: 75846497002721615035084145124908598465369203372776925311647388682844879171224833237256121036877550622279810544619158738093477736034336287973652825766537515529926134203612598743638267619115413828468728890028530344522803914001620771820857767871182791491227971896146576103323275110095954692409235604090210690969
e: 27944359928402522493204476374964417329825972880038323978440237532019659924445653956494595397354858130911825463636941069777455687844806506391989580404333650093538551605534291974043515754379911987206048486025556154618448298808333520915498355195556782591000561713322541699327851567281929797275512373758492449441
```

The value of e is very large as compared to what we see in classic RSA so i googled about the e and fond out that it can be vulnerable to Wiener Attack.
After a bit of googling I found ```https://github.com/orisano/owiener``` which is python library to perform weiner attack so for checking if this is vulnerable to
Weiner attack do ```e<n``` and if it returns true i.e., if e is less than n it is vulnerable to this attack. So I wrote a python script

```
#!/usr/bin/env python3

import owiener

c = 10053284367692092408060534432233781784294923528212355187383526910927871066651583744637289085781456421980473491209482413938046982135479068839655873058602979592685277822007493317921218411757164957737640844095430827381520163245525364943143755308164241740933293587239366002651923964673511284584594740402129716515
n = 75846497002721615035084145124908598465369203372776925311647388682844879171224833237256121036877550622279810544619158738093477736034336287973652825766537515529926134203612598743638267619115413828468728890028530344522803914001620771820857767871182791491227971896146576103323275110095954692409235604090210690969
e = 27944359928402522493204476374964417329825972880038323978440237532019659924445653956494595397354858130911825463636941069777455687844806506391989580404333650093538551605534291974043515754379911987206048486025556154618448298808333520915498355195556782591000561713322541699327851567281929797275512373758492449441

d = owiener.attack(e, n)

m = pow(c,d,n)
print(bytes.fromhex(hex(m)[2:]).decode('utf-8'))
```
Running the script gave me the flag

flag:```picoCTF{bad_1d3a5_2438125}```
